// Event messaging drafts: the room request, flyer prompt, catering request,
// Slack posts and NPS survey email that every Exos event needs. Each draft is
// generated separately so they can run in parallel and be regenerated one at
// a time. William's own past messages are the style guide.
const Anthropic = require("@anthropic-ai/sdk").default;

const MODEL = process.env.EVENT_DRAFT_MODEL || "claude-opus-5-5";
const EFFORT = process.env.EVENT_DRAFT_EFFORT || "low";

const DRAFTS = [
  {
    key: "roomEmail",
    step: "room",
    instructions: `Write the room and equipment booking email to Sahar Rasheed (Site Operations).
Follow the "Event Space Booking and Equipment Email to Sahar" example closely: warm one-line opener with the event type, day, date and time; "Could we please arrange to have the following items for the event." followed by a bulleted equipment list; an "Event Details:" bulleted list (Event Title, Date, Time, plus Location requested and expected attendance when known); close by asking which location works and whether she needs anything to confirm the booking. Sign off "Best,\\nWilliam Farparan".`,
  },
  {
    key: "flyerPrompt",
    step: "flyer",
    instructions: `Write a ready-to-paste image-generation prompt William can drop into Google Nano Banana or Adobe Firefly to create the event flyer/poster for Slack and print.
House style range (pick the one that fits this event, or blend): (1) gritty high-contrast black and red competition poster with sketched athletes and heavy distressed condensed type, like the "ADEX GAMES" leaderboard; (2) warm kraft-paper background with huge bold red display type, a script accent word, and one real candid photo, like "BIKE to WORK"; (3) vibrant flat illustrated scene in saturated pinks/purples/teals with a rounded-rectangle info card, like "Breakers Bound".
Output these labelled sections, plain text:
PROMPT: one dense paragraph describing composition, style, palette, typography and mood. Portrait 8.5x11 (2550x3300 px).
TEXT ON THE POSTER: every line of text to render, exactly as it should appear, one per line (event name as the headline, date, time, location, a one-line hook, and the footer "#sf-wellness-center  @exo08583 @exo46532 @exo78564").
LAYOUT: where each text element sits; keep the top-right corner clear for the Exos | Adobe logo lockup.
AVOID: no logos or brand marks generated by the model, no extra or misspelled words, no watermarks.
FINISHING NOTE: one line reminding him to place the official Exos | Adobe logos after generating and to proof every word.`,
  },
  {
    key: "cateringEmail",
    step: "catering",
    needs: (event) => event.catering_needed,
    instructions: `Write the catering request email to Joshua Dougherty (Culinary, Bon Appétit).
Follow the "Event Catering Booking Request Email to Josh" example closely: "Hi Joshua," then "Hope you're doing well!"; one sentence saying Exos is hosting the event on the date and would love to partner with Bon Appétit on the catering; an "Event Details" bulleted list (Event, Date, Time, Location, Estimated Catering Count, Budget); a sentence describing the menu vision tied to the event theme and Exos pillar, then a bulleted menu. Use his menu ideas when given; otherwise propose 4-5 light items that fit the pillar. Invite seasonal recommendations within budget, then "Looking forward to hearing your thoughts. Thanks in advance!" and "Best,\\nWilliam Farparan".`,
  },
  {
    key: "slack1",
    step: "slack-1",
    instructions: `Write the INITIAL Slack announcement, posted about 2-3 weeks before the event (like "Kickball Classic Event - 1-2 Weeks Before Post").
Shape: an ALL-CAPS headline with one emoji anchor and a short hook ("EVENT NAME — GET INVOLVED!"); a 2-3 sentence opener that introduces the event and why it matters; an emoji-anchored detail block with what, when (day, date, time) and where; a clear call to action (register, RSVP, or save the date, with the link or [Registration link]); a short community closer line; then the sign-off.`,
  },
  {
    key: "slack2",
    step: "slack-2",
    instructions: `Write the SECONDARY Slack post, about 10 days before (like "Kickball Classic Event - 10 Days Before Post").
Lead with the countdown ("just 10 days away, SF!"), restate the value, then 2-3 emoji-anchored ways to get involved, each with a bold all-caps label (*PLAY KICKBALL:*-style) and a sentence or link. Add one relevant cross-promotion line (for example the SF Group Exercise Schedule) when it fits. End with the community closer and sign-off.`,
  },
  {
    key: "slack3",
    step: "slack-3",
    instructions: `Write the THIRD Slack post, 1-3 days before (like the "1 Week Before" and "Day Before" posts).
Urgent, final-push energy: an all-caps headline ("BIG GAME WEEK — ..."), "this Friday"-style framing using the real weekday, any last logistics, the same emoji-anchored labelled call-to-action blocks, a punchy three-part all-caps rally line ("THIS FRIDAY. ONE FIELD. ONE COMMUNITY."-style, adapted to this event), the closer and sign-off.`,
  },
  {
    key: "slackDayOf",
    step: "day-of",
    instructions: `Write the DAY-OF Slack post, published the morning of the event.
Short and energetic: an all-caps "TODAY" headline with an emoji anchor, one or two lines on what is happening, a tight emoji-anchored block with the time and exact location, a line asking people to swipe their badge at check-in, a one-line closer, and the sign-off.`,
  },
  {
    key: "npsEmail",
    step: "survey",
    instructions: `Write the post-event survey email, sent within 3 days of the event to attendees (BCC).
Follow the "Post event Microsoft Forms NPS Survey email draft" example closely: "Hi all,"; thank everyone who attended and supported the event (name it); ask them to complete the short survey, noting their input helps create even better experiences; "Please take a few moments to complete the survey using the link below:" then "[Microsoft Forms survey link]" on its own line; thank those who already completed it; "Best regards,\\nYour Wellness Team".`,
  },
];

const DRAFT_KEYS = DRAFTS.map((d) => d.key);

const SYSTEM = `You write event messaging for William Farparan, a Certified Performance Coach with Exos, on-site at Adobe's San Francisco wellness centers (Hooper Wellness Center and 601 Townsend). Each request asks for ONE piece of messaging for ONE event. Write only that piece, ready to paste, with no preamble or commentary.

PEOPLE
- Sahar Rasheed - Site Operations; room and space booking.
- Joshua Dougherty - Culinary (Bon Appétit); catering.
- Michelle Bariao - Account Manager; escalations and anything with no existing SOP.
- Coaches: Antoine Robinson (@exo08583), Christopher Pham (@exo78564), William (@exo46532).

VOICE
- The company is "Exos" in title case in body copy. Direct, confident, warm, a little wry. No corporate filler.
- Slack posts sign off exactly:
Your Wellness Team,
@exo08583 @exo78564 @exo46532
- Slack formatting: plain text with emoji; *single asterisks* for bold; no markdown headings; put links on their own line as "Label: url".
- Emails: first line "Subject: ..." then a blank line, then the body.

FACTS
- Use only the event facts provided. Never invent prices, rooms, headcounts, links, names or times. When something is missing, use a short bracketed placeholder like [Location] or [Registration link].
- Write dates as "Tuesday, September 8" and times as "11:30 AM - 2:00 PM".

WILLIAM'S PAST MESSAGES (match this structure and tone)

--- Event Space Booking and Equipment Email to Sahar ---
Hi Sahar,
We've got a tabling event for the EXOS on Tuesday, Sept 8th, 11:30am-2:00pm. I wanted to reach out and confirm the following works.
Could we please arrange to have the following items for the event.
- 1x Table
- 2x Chairs
- 1x PA System
Event Details:
- Event Title: EXOS Tabling
- Date: Tuesday, September 8
- Time: 11:30 AM - 2:00 PM
Let me know what location works and if there's anything you need from me to confirm the booking.
Best,
William Farparan

--- Event Catering Booking Request Email to Josh ---
Hi Joshua,
Hope you're doing well!
EXOS is hosting a Wellness Massage Event on Tuesday, August 18, and I'd love to partner with Bon Appétit on the catering.
Event Details
- Event: Wellness Massage Event
- Date: Tuesday, August 18
- Estimated Massage Appointments: ~25
- Estimated Catering Count: 30 ~ guests
- Budget: Approximately $450
For the menu, I'm envisioning light, fresh bites that fit the wellness and recovery theme while allowing guests to snack throughout the event. Here's what I had in mind:
- Grilled chicken pesto tea sandwiches
- Arugula, avocado & parmesan salad
- Truffle Yuca fries with verde glaze or spicy aioli
- Lavender lemonade
- Probiotic drinks
If there are any seasonal recommendations or menu adjustments you think would pair well while staying within budget, I'm definitely open to your suggestions.
Looking forward to hearing your thoughts. Thanks in advance!
Best,

--- Slack: Kickball Classic, 1-2 weeks before ---
KICKBALL CLASSIC — GET INVOLVED!
We're getting ready for the Adobe Kickball Classic, and there are a few ways to join the fun and support Blood Cancer United!
CARD-MAKING VOLUNTEER EVENT — TOMORROW (8/18)
Landmark Café (Near Velcro)
11:30 AM–2:30 PM
Stop by anytime, make a card, and help us create thoughtful messages for individuals and families impacted by blood cancer. All supplies will be provided!
CAN'T MAKE IT TOMORROW?
You can still support the cause by donating through Adobe Benevity:
Donate to Blood Cancer United
WANT TO PLAY KICKBALL?
Teams and Free Agents are welcome! No team? No problem — register and we'll help get you in the game.
Event details + Kickball registration:
Adobe Kickball Classic Express Page
Play Hard. Give Back. Build Community.

--- Slack: Kickball Classic, 10 days before ---
ADOBE KICKBALL CLASSIC - GET IN THE GAME!
The Adobe Kickball Classic is just 10 days away, SF! Let's bring that unstoppable Adobe community energy to support Blood Cancer United! We have a few ways for you to get involved, give back, and finish strong:
PLAY KICKBALL: Teams and Free Agents are welcome! No team? No problem - register on the Adobe Kickball Classic Express Page and we'll get you in the game.
Adobe Kickball Express Page
FUEL THE FIGHT: Can't make the event? The game is only 10 days away, and you can still power the cause! Please make sure to use this link to donate to blood cancer research through Adobe Benevity:
Donate to Blood Cancer United
CARD-MAKING: Stop by Hooper Wellness Center to create thoughtful messages for individuals and families impacted by blood cancer. All supplies are provided, so just bring your compassion! Check out the attached image for some creative inspiration and a reminder of how much your words matter.
Need to prep your body for the field? Check out the San Francisco Group Exercise Schedule to find the perfect class to optimize your recovery and performance.
Play Hard. Give Back. Build Community. See you on the field!
Your Wellness Team,
@exo08583 @exo78564 @exo46532

--- Slack: Kickball Classic, 1 week before ---
BIG GAME WEEK — ADOBE KICKBALL CLASSIC!
We're officially ONE WEEK away, SF! The Adobe Kickball Classic hits the field next week, and this is our final push to PLAY, GIVE BACK, and SHOW UP in support of Blood Cancer United.
GET IN THE GAME: We're still looking for players! Teams and Free Agents are welcome. No team? No problem — register and we'll help get you into the game.
Register here:
Adobe Kickball Classic Express Page
FUEL THE FIGHT: Whether you're playing or cheering from the sidelines, you can support blood cancer research through Adobe Benevity. Every contribution helps us push the mission forward.
Donate here:
Support Blood Cancer United
MAKE AN IMPACT: Stop by the Hooper Wellness Center to create a card and share an encouraging message with individuals and families impacted by blood cancer. Supplies are provided — just bring your creativity and compassion.
ONE WEEK. ONE FIELD. ONE COMMUNITY.
Let's finish this push strong, SF. Play Hard. Give Back. Build Community. See you on the field!
Your Wellness Team
@exo08583 @exo78564 @exo46532

--- Slack: Kickball Classic, day before ---
BIG GAME WEEK — ADOBE KICKBALL CLASSIC!
The Adobe Kickball Classic hits the field this Friday, and this is our final push to PLAY, GIVE BACK, and SHOW UP in support of Blood Cancer United.
Just a heads up for anyone wondering, the teams are currently being created! You will receive an email shortly with the official list of teams and your rosters.
GET IN THE GAME: We're still looking for players! Teams and Free Agents are welcome. No team? No problem — register and we'll help get you into the game.
Register here: Adobe Kickball Classic
FUEL THE FIGHT: Whether you're playing or cheering from the sidelines, you can support blood cancer research through Adobe Benevity. Every contribution helps us push the mission forward.
Donate here: Support Blood Cancer United
MAKE AN IMPACT: Stop by the Hooper Wellness Center to create a card and share an encouraging message with individuals and families impacted by blood cancer. Supplies are provided — just bring your creativity and compassion.
THIS FRIDAY. ONE FIELD. ONE COMMUNITY.
Let's finish this push strong, SF. Play Hard. Give Back. Build Community. See you on the field or around Townsend!
Your Wellness Team
@exo08583 @exo78564 @exo46532

--- Post-event Microsoft Forms NPS survey email ---
Hi all,
Once again, the EXOS team would like to thank everyone who attended and supported the Annual Kickball Classic for Blood Cancer United.
If you have not completed our survey, we'd love to hear your feedback. Your input is incredibly valuable and helps us create even better experiences moving forward.
Please take a few moments to complete the survey using the link below:
[Survey Link]
If you've already completed the survey, thank you so much for your time and insights!
Best regards,`;

function dateKey(value) {
  if (!value) return "";
  if (value instanceof Date) return value.toISOString().slice(0, 10);
  return String(value).slice(0, 10);
}

function longDate(key) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(key)) return "[Date]";
  return new Intl.DateTimeFormat("en-US", {
    timeZone: "UTC",
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  }).format(new Date(`${key}T12:00:00Z`));
}

function clockLabel(value) {
  if (!/^\d{2}:\d{2}$/.test(String(value || ""))) return null;
  const [h, m] = value.split(":").map(Number);
  return `${h % 12 || 12}:${String(m).padStart(2, "0")} ${h >= 12 ? "PM" : "AM"}`;
}

// Plain-language fact sheet for one event; missing values are named so the
// model uses a placeholder instead of guessing.
function eventFacts(event) {
  const start = clockLabel(event.start_time);
  const end = clockLabel(event.end_time);
  const lines = [
    `Event name: ${event.name}`,
    `Date: ${longDate(dateKey(event.event_date))}`,
    `Time: ${start ? (end ? `${start} - ${end}` : start) : "not set"}`,
    `Location: ${event.location || "not set"}`,
    `Exos pillar: ${event.pillar || "not set"}`,
    `What it is: ${event.description || "not provided"}`,
    `Expected attendance: ${event.expected_attendance || "not set"}`,
    `Equipment needed: ${event.equipment || "not specified"}`,
    `Catering: ${event.catering_needed ? "yes" : "no"}`,
  ];
  if (event.catering_needed) {
    lines.push(`Catering budget: ${event.catering_budget || "not set"}`);
    lines.push(`Menu ideas: ${event.menu_ideas || "none given"}`);
  }
  lines.push(`Registration / info link: ${event.event_link || "none"}`);
  if (event.needs_vendor)
    lines.push("New vendor or no existing SOP: yes (Michelle approves first)");
  return lines.join("\n");
}

function draftSpec(key) {
  return DRAFTS.find((d) => d.key === key) || null;
}

async function generateDraft(event, key) {
  const spec = draftSpec(key);
  if (!spec) throw new Error(`Unknown draft: ${key}`);
  const client = new Anthropic();
  const response = await client.beta.messages.create({
    model: MODEL,
    max_tokens: 16000,
    output_config: { effort: EFFORT },
    // Re-run on a fallback model if a safety classifier declines.
    betas: ["server-side-fallback-2026-07-01"],
    fallbacks: "default",
    system: [
      { type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } },
    ],
    messages: [
      {
        role: "user",
        content: `EVENT FACTS\n${eventFacts(event)}\n\nTASK\n${spec.instructions}`,
      },
    ],
  });
  if (response.stop_reason === "refusal")
    throw new Error("Claude declined to write this draft. Try regenerating.");
  const text = response.content
    .filter((block) => block.type === "text")
    .map((block) => block.text)
    .join("\n")
    .trim();
  if (!text) throw new Error("Claude returned an empty draft.");
  return {
    text,
    usage: {
      inputTokens: response.usage?.input_tokens || 0,
      outputTokens: response.usage?.output_tokens || 0,
    },
  };
}

module.exports = { DRAFTS, DRAFT_KEYS, draftSpec, eventFacts, generateDraft };
